layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: sonika-arora
  # mastodon: your_username
  medium: thegirlinthepinkscarf
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Machine Learning
    web_url: https://github.com/Machine-Learning-Tokyo/Interactive_Tools
    image_url: https://upload.wikimedia.org/wikipedia/commons/d/d5/Hey_Machine_Learning_Logo.png

  - name: Web design
    web_url: https://www.entrepreneur.com/article/339921
    image_url: https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQWoB4TPaOrCBn8_19aOTnSQokmY-0E1a4aWJ2m9t7kg6ilmset

  - name: Cloud Computing
    web_url: https://www.sungardas.com/globalassets/_multimedia/document-file/sungardas-the-12-best-cloud-computing-articles-of-the-year-white-paper.pdf?version=1
    image_url: https://image.shutterstock.com/image-vector/cloude-flat-icon-single-high-260nw-741196795.jpg
